### ISSUE TITLE
VSCode 1.4.0

### ISSUE THREAD

**Issue by anarchyonline** [stef-levesque/vscode-hexdump#1]
Having trouble getting this to work with 1.4.0.
In fact, using the keyboard shortcuts does nothing at all.

System is OS X 10.11.6 with VSCode 1.4.0

**Comment by stef-levesque** [comment]
Can you confirm right-click on a file and selecting "Show hexdump for file" works ?

**Comment by anarchyonline** [comment]
Update to previous report: Your extension works **except** for files that are **not part** of a folder that was opened by VSCode. From 1.4.0 a user can also open files directly in a tab -- without having to open the file's parent folder first as per above.

<img width="372" alt="screen shot 2016-08-16 at 16 42 24" src="https://cloud.githubusercontent.com/assets/5250664/17703069/a9d3d70c-63d0-11e6-8e65-73dac0363372.png">

<img width="341" alt="screen shot 2016-08-16 at 16 42 35" src="https://cloud.githubusercontent.com/assets/5250664/17703071/ae4051b2-63d0-11e6-803e-5f5ced0986b0.png">

**Comment by stef-levesque** [comment]
Thanks for precision, much appreciated!

Unfortunately, Code Extensions API do not allow to add context menu outside of the folder section.
(AFAIK, @jrieken might know how...)
So right now, the fastest workaround is to right-click, "Copy Path", run "hexdump.hexdumpFile" and 
paste it.

As for the shortcut not working, a fix is on the way.

**Comment by jrieken** [comment]
Yeah, sorry that a current limitation of the `explorer/context` menu.

**Comment by stef-levesque** [comment]
Shortcut fixed in release 0.1.0, please update.
