### ISSUE TITLE
Can't open hexdump in 'open editors'

### ISSUE THREAD

**Issue by liigo** [stef-levesque/vscode-hexdump#10]
![hexdump-issue](https://cloud.githubusercontent.com/assets/346530/19719367/2d047e76-9b9c-11e6-9b3e-63874dd47298.png)

**Comment by stef-levesque** [comment]
This is a known issue, VSCode do not allow to add commands to the 'Open Editors' section yet (see issue #1)

**Comment by stef-levesque** [comment]
Closing it for now. Until VSCode fix the issue, please use the 'Show Hexdump' icon
![Title Icon](https://raw.githubusercontent.com/stef-levesque/vscode-hexdump/master/images/title-icon.png)

**Comment by liigo** [comment]
But I can't find that icon, at the top-right corner of editor. How to display it? @stef-levesque

**Comment by stef-levesque** [comment]
Please make use you are using VSCode 1.7.1 and vscode-hexdump 1.1.3

**Comment by liigo** [comment]
Got it. Thank you!
