### ISSUE TITLE
UI enhancement

### ISSUE THREAD

**Issue by wm1** [stef-levesque/vscode-hexdump#13]
- When click "show hexdump" command, the current document should be "switched" to hex view, instead of opening a new, separated hexdump document. Click the command again, the hex view should switch back to the original text window.
- The first row that displays column offset should be fixed and not scroll with other rows
- The hex inspector when hover over the data is distracting and useless. Please remove it.
- The auto highlight of all character that are identical to the one under the current cursor is distracting as well. This is especially true when it is a common char e.g. 0x20 blank space. Please disable it
- Edit value under cursor should happen in place inside the document under the cursor, instead of in a separate input box. Also I should be able to edit multiple consequent bytes by just typing along.
- After editing value, the hex dump file should be marked as "modified" visually
- Ctrl-S should save to the original file name without prompt

**Comment by stef-levesque** [comment]
You have some valid points here. Unfortunately, most of them are currently not feasible in a vscode extension.

Although, here's what in my control:
- Optional Hex Inspector
  - I can add a setting to enable or not the Inspector when hovering content
- Marked as "modified" visually
  - I cannot display the 'modified' dot in the document tab, but I can add `(modified}` in the Hex status bar
- Save without prompt
  - I can remap `Ctrl-S` to save without prompt, and `Ctrl-Shift+S` to Save As...

**Comment by stef-levesque** [comment]
Please update to version 1.1.4

**Comment by wm1** [comment]
v1.1.4 - Marked when (modified) in the status bar (#13)

If it is impossible to display the 'modified' dot on the tab list / open editor, then just do not do it. Adding (modified) to the status bar is inconsistent with the overall VSCode UI, and I'm afraid few people will be able to recognize it easily.

Beside, the status is not working as expected:
- Open file. View hex. Modify it. Close the file --> Expect some warning "File is modified, save it first?", but that is not happening
- Close both original file and the hex one. Open a *different* file. View hex. --> The status bar still displays (modified), which is not expected

Also can you change the popup menu "export to binary file" to simply "save as"?
