### ISSUE TITLE
UTF8 (or other Unicode encoding) display?

### ISSUE THREAD

**Issue by phindle** [stef-levesque/vscode-hexdump#14]
Would it be possible to show UTF8 symbols in the popup window?

This could be configured via a  "hexdump.characterEncoding" setting?
hexdump.characterEncoding: "UTF8",
hexdump.characterEncoding: "UTF16",
hexdump.characterEncoding: "ASCII",
hexdump.characterEncoding: "Shift-JIS",
etc

**Comment by stef-levesque** [comment]
So here's the plan.

A `string` section would appear in the Hex Inspector, if the user hover a selection.
It will try to display it as a UTF-8 string, unless configured with `hexdump.charEncoding`
Supported encoding can be found in [node-iconv docs](https://github.com/bnoordhuis/node-iconv)

The end result would be something like that:
![hover-string](https://cloud.githubusercontent.com/assets/7251102/23580572/534e3b62-00d2-11e7-8b31-631c92378ede.png)

Would that make sense ?

**Comment by stef-levesque** [comment]
New setting `hexdump.charEncoding` available in version 1.2.0

**Comment by phindle** [comment]
Perfect - really appreciate you implementing this! I think it's a great improvement.
