### ISSUE TITLE
'Show Hexdump' right-click option in 'Open Editors' sidebar

### ISSUE THREAD

**Issue by chrisdarth** [stef-levesque/vscode-hexdump#16]
Hi! This is really useful, thanks!

Is it possible to have a right-click option for 'Show Hexdump' in 'Open Editors' sidebar? This would allow me to open the file in VS Code, and just rightclick it (as opposed to opening the folder and locating the file).

Cheers,
CD

**Comment by stef-levesque** [comment]
Unfortunately, VSCode doesn't allow for that (see #10 )

But you can right-click on the file tab, or use the upper-right icon to do the same:

![title-icon.png](https://raw.githubusercontent.com/stef-levesque/vscode-hexdump/master/images/title-icon.png)
