### ISSUE TITLE
Feature request: Update hex/text view as the file is edited

### ISSUE THREAD

**Issue by BillDenton** [stef-levesque/vscode-hexdump#17]
Make edits in the text view or hex view show up in the other view. At the moment, I have to save the text file and re-open the hex view. Would it be possible to make the updates appear in both views as it changed.

**Comment by stef-levesque** [comment]
Unfortunately, the code relies a lot on working with the file, not the ActiveEditor content. Having a Hex view on the side couldn't provide the same amount of functionality.

It is not impossible, but not trivial either.

**Comment by Vad1us** [comment]
Hi. Live update is not needed so much, but: when file is edited, i try to reopen "hexdump" but there is no updates. May be you can add the feature? Every press "show hexdump" it will update, because right now it shows old version of file all the time. Thanks.

**Comment by stef-levesque** [comment]
@Vad1us if you edit _and save_ the file, the "hexdump" will be updated.
If this is not the case, please create a different issue, and provide your OS and VSCode version.

**Comment by stef-levesque** [comment]
Fixed in version 1.8.0
