### ISSUE TITLE
Feature request: Show Hexdump command uses currently active file

### ISSUE THREAD

**Issue by AndreasHassing** [stef-levesque/vscode-hexdump#20]
It would be nice if running the "Show Hexdump" command opened the hex dump of the currently active file.

I rarely move my mouse while working, so having to right-click a file, or click a button in the top right corner is super awkward for me (and, I'm guessing, a lot of other people).

I'd make a PR, but my time is limited these days 😞.

**Comment by stef-levesque** [comment]
I feel your pain :)

If you don't mind having to press the `Enter` key after `Show Hexdump` shortcut (default is Ctrl-Alt-Shift-H), I can pre-fill the edit box with the currently active text editor, instead of the workspace root path.

**Comment by AndreasHassing** [comment]
Nice! That could be a useful compromise :)

**Comment by stef-levesque** [comment]
Please update to version 1.2.0

**Comment by AndreasHassing** [comment]
Thank you :) that helps!
