### ISSUE TITLE
"broken" HexDump button on Extension description page

### ISSUE THREAD

**Issue by SailorMax** [stef-levesque/vscode-hexdump#21]
Steps:
1. Open Extensions tab
2. click on any extension

Expected: Extension description page without HexDump button.

Actual: Extension description page with HexDump button, which does not work.

**Comment by adyavanapalli** [comment]
@SailorMax Can you provide a screenshot of what you're referring to?

**Comment by SailorMax** [comment]
Button in top right corner, near "..." button. In row with opened files tabs.

**Comment by adyavanapalli** [comment]
![image](https://cloud.githubusercontent.com/assets/8067797/23618967/2438da00-0260-11e7-8d53-e5b4921a2864.png)

@SailorMax Is this what you mean?

**Comment by SailorMax** [comment]
@adyavanapalli Righter. Above document vertical scroll.

**Comment by adyavanapalli** [comment]
![image](https://cloud.githubusercontent.com/assets/8067797/23619165/c2aa56e6-0260-11e7-8da8-15e0d1ef6d7b.png)

@SailorMax  Ohh.. you're saying that the hexdump button should *not* appear in this instance, and even though it does, it does nothing?

**Comment by SailorMax** [comment]
@adyavanapalli Yes.

**Comment by adyavanapalli** [comment]
@SailorMax This does not cause any *significant* problem to the user, though it should be fixed. What do you think @stef-levesque ?

**Comment by SailorMax** [comment]
@adyavanapalli UI should to be clear.
Author of GitLens fixed same problem: https://github.com/eamodio/vscode-gitlens/issues/38
VSCode authors in the queue: https://github.com/Microsoft/vscode/issues/22059
HexDump is last in my case :)

**Comment by stef-levesque** [comment]
Well, I'm at work right now, but I'll try and fix that tonight :)

**Comment by adyavanapalli** [comment]
@SailorMax Agreed 👍

**Comment by stef-levesque** [comment]
Fixed in version 1.2.1
