### ISSUE TITLE
Open a ~15MB file

### ISSUE THREAD

**Issue by rodrigokiller** [stef-levesque/vscode-hexdump#22]
I know that this file is really big, but, I dont know why I can open it in Notepad++ with hex plugin, for example, and here I cant.
Thanks

**Comment by stef-levesque** [comment]
Unfortunately, it's due to VS Code limitation, see Microsoft/vscode#21869

**Comment by rodrigokiller** [comment]
Hello. I think that it is no more a VS Code limitation. I tried and now I can open files more than ~15MB. I tried a 26 MB file and it opened in VS Code. And, in the link provided by you, alexandrudima could not reproduce the issue and the issue was closed.

**Comment by stef-levesque** [comment]
Thanks to the memory fixes in Microsoft/vscode#30180 , the bottleneck is no more coming from memory, but from the time it takes to process the output of `hexdump` and display the actual `TextDocument`.

i.e. If you set `hexdump.maxLineCount` to 1000000, you can't open `hexdump` on a large file (~15Mb). But if you first open it with the default `hexdump.maxLineCount` and once it is open, increase `hexdump.maxLineCount` to 1000000, it will eventually update the already-opened `hexdump` TextDocument.

I'll take another look, and see if I can provide a limited "preview" before loading the whole file in the background.

**Comment by rodrigokiller** [comment]
@stef-levesque thanks Stef, I know that I can use a editor that focus only in the hex edition, but, I really love Visual Code and it would be nice to have an actual good option to those old hex editors.

**Comment by stef-levesque** [comment]
@rodrigokiller version 1.6.0 of this extension should better handle large files. You can try to set `hexdump.sizeDisplay` to `15728640` for displaying a full 15Mb file, but due to a VSCode limitation, the color syntax won't work.
