### ISSUE TITLE
Cannot save edits in .bin file

### ISSUE THREAD

**Issue by bitswype** [stef-levesque/vscode-hexdump#23]
I really like the look and feel of this hex editor in VSCode.  It has many of the features I am looking for and is a vital tool doing embedded work. 

I have run across a small problem where edits made to a .bin file are not being saved.

Steps to reproduce:
1.) create a text file with a single word in it.  I chose "hello"
2.) save the file, then change the file extension from .txt to .bin
3.) open the .bin file in VS code and open the hexdump
4.) edit any byte by right clicking and selecting "edit value under cursor" or by hitting shift+enter (I changed "hello" to "henlo" by modifying byte 2 from 0x6C to 0x6E
5.) save the file.  Save all, save as, save, ctrl-s, any way you want.
6.) close the file
7.) open the file
8.) observe that the file is unchanged (it still says "hello")

This problem seems to occur even if the file is a .txt file.

Win 7, 64 bit
hexdump for VSCode v1.2.1
VSCode v1.10.2

**Comment by stef-levesque** [comment]
Can you try to use the `Export to Binary File..` command ?
You can use the right-click menu, or ctrl-shift-s shortcut in a hexdump document.

**Comment by bitswype** [comment]
That works.  Am I doing something wrong by trying to save the file?

**Comment by stef-levesque** [comment]
There is no way (that I know of) for a extension to hijack the save event of a TextDocumentContentProvider. The best I can do is to assign `export` command to similar shortcuts.

As a side note, it seems the file refresh doesn't work properly. I'll have a look.

**Comment by MobiusIQ** [comment]
I guess I got confused because under commands you list:

- `save` (`ctrl+s`, `cmd+s`) Save file

Is that meant for something else?

**Comment by stef-levesque** [comment]
This seems fixed now with version 1.3.0. Please update.
