### ISSUE TITLE
Cannot view HEX in file accessed on UNC path.

### ISSUE THREAD

**Issue by Elsewhere42** [stef-levesque/vscode-hexdump#25]
When I open a file on my local C:\ drive, I am able to view the HEX contents of a test.txt file.

If I copy this same file to a UNC path Hexdump will not appear with the hex content of the file.  

Example:  \\\\MyServer\MyShare\text.txt

**Comment by stef-levesque** [comment]
VS Code doesn't play nice with UNC path (see [UNC issues](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20UNC) )

But there might be something I can do on the Extension side to alleviate that.

**Comment by stef-levesque** [comment]
Should be fixed with version 1.2.2, please update.

**Comment by Elsewhere42** [comment]
Tested and Confirmed v1.2.2 working with UNC path.  Much appreciated!
