### ISSUE TITLE
Feature request: do not autosave

### ISSUE THREAD

**Issue by warpdesign** [stef-levesque/vscode-hexdump#27]
Right now, when choose "edit value under cursor" and changing the value, the modification is immediately written to disk: it's quite different from the behavior of VSCode which won't automatically (unless you have files.autoSave set to 'on') save your file but put a "modified" marker next to the filename instead.

How about only autoSaving when the files.autoSave option is set?

**Comment by warpdesign** [comment]
Looks like there is no autoSave actually: since there was no "modified" marker appended on the original file nor the ".hexdump" tab, and since that closing the ".hexdump" tab and opening it again shows the modified state, I thought it had been saved.

**Comment by stef-levesque** [comment]
You are right, identifying the document as being modified would help the user to better understand the situation. Hopefully, renaming the tab and colorize modifed bytes (#28) should help
