### ISSUE TITLE
Feature Request: Open Binary Files

### ISSUE THREAD

**Issue by thelehhman** [stef-levesque/vscode-hexdump#32]
It would be great if this extension would open binary files by default, i.e. instead of this message:
<img width="735" alt="screen shot 2017-09-18 at 7 19 12 pm" src="https://user-images.githubusercontent.com/2987087/30545103-4ae913e6-9ca6-11e7-9163-ba715d74dff8.png">
You get the hexdump, the way sublime text handles it.

**Comment by stef-levesque** [comment]
This is currently a limitation of VSCode, but this is being worked on.
On the bright side, next version of VSCode should allow extension to use the Open/Save dialog, which mean you can skip this error message.

**Comment by thelehhman** [comment]
Alright, be sure to add it once its feasible :)
