### ISSUE TITLE
Files association not really working

### ISSUE THREAD

**Issue by huettenhain** [stef-levesque/vscode-hexdump#33]
Hey! Thanks for the great plugin. I have a very minor issue with it: Even though I set
```json
  "files.associations": {
    "*.dmp": "hexdump"
  }
```
in my settings, `*.dmp` files are *not* opened in the hexdump by default, I always have to select the hexdump button in the top right corner. Am I doing something wrong?

**Comment by stef-levesque** [comment]
This extension is using `scheme` to specify when to use the `hexdump` display.
Associating `*.dmp` to `hexdump` will only enable the syntax highlighting.

I don't think there is a way in VSCode to force a file type to be opened with a specific `scheme`

**Comment by huettenhain** [comment]
Alright, I see. Would be really useful if certain files would directly open in hexdump, I hope someone knows of a way to achieve this.

**Comment by stef-levesque** [comment]
There is already an issue/feature request on VSCode for that (see microsoft/vscode#12176)
But there is not much traction on this.

**Comment by huettenhain** [comment]
I+1'ed it, not much more we can do I suppose. Thanks a lot anyway!

**Comment by stef-levesque** [comment]
Closing for now, will re-open if VSCode expose an API for that.

**Comment by BlueGGuy** [comment]
https://code.visualstudio.com/api/extension-guides/custom-editors

**Comment by kaedros** [comment]
the other editor does it how?

https://marketplace.visualstudio.com/items?itemName=ms-vscode.hexeditor

**Comment by stef-levesque** [comment]
iirc, you can now right-click on a file and 'open with editor', then click on the setting icon to select the default one.
