### ISSUE TITLE
Recommendation: It would be nice to have a pretty icon 😄

### ISSUE THREAD

**Issue by Elderry** [stef-levesque/vscode-hexdump#35]
This extension is great for me, thanks for the author. Just think the icon can be better.

**Comment by stef-levesque** [comment]
How about something like that ?

![image](https://user-images.githubusercontent.com/7251102/32067296-b136b5d2-ba50-11e7-8d03-a4c1b3f0731c.png)

**Comment by Elderry** [comment]
It's better then the old one. I think icon shouldn't have many small characters, thus can be easy to distinguish at small size.

**Comment by stef-levesque** [comment]
New icon in version 1.6.0
