### ISSUE TITLE
Incoherent cache

### ISSUE THREAD

**Issue by Yanpas** [stef-levesque/vscode-hexdump#39]
I've a program that truncates and writes some content to a file. If I right-click file and press show hexdump the contect will be stale.

**Comment by stef-levesque** [comment]
Are you closing all hexdump tabs before showing a new hexdump ?

**Comment by Yanpas** [comment]
Yes, I was closing them. I've reloaded vs code window and cannot reproduce. I will reopen issue when I will have steps to reproduce

**Comment by sergburn** [comment]
For me it occurs every time. Debugging C code, the application deletes and recreates small binary file on each run. But once opened its hexdump does not change ever until "Reload Window" is done. Even if the tab is closed and the dump is reopened. I also tried "File: Revert File" from command palette - nothing works.

Mac OS 10.13.6, VSCode 1.29.1, hexdump v1.7.2.
Would be great if you re-checked this case. If you need some other information from me, please tell.

**Comment by youkaichao** [comment]
It bothers me, too.

Mac OS 10.13.6 (17G6030)
VSCode  1.34.0 (1.34.0)
hexdump 1.7.2

**Comment by PhyX-Meow** [comment]
Same here

**Comment by stef-levesque** [comment]
TBH, since Microsoft now makes its own [Hex Editor](/microsoft/hexeditor), I'm thinking about deprecating my own extension.

**Comment by WebFreak001** [comment]
the performance on Microsoft's hex editor has been a lot worse when I tried it and I love the hover on this one + so far always used this one instead, can you reconsider deprecating this?
