### ISSUE TITLE
Every file is in read only mode

### ISSUE THREAD

**Issue by ullenboom** [stef-levesque/vscode-hexdump#51]
Changing bytes is not possible. Is this the intended default?

![image](https://user-images.githubusercontent.com/5071169/48966868-c6146580-efd8-11e8-8c41-bf5218522b0e.png)

**Comment by stef-levesque** [comment]
The hexdump buffer is read-only by default.
But you can edit the hexadecimal value under your cursor with the following command:
`editValue (shift+enter) Edit Value Under Cursor`

Edited values will display in red. You should then export or save the buffer with one of the following command.
`exportToFile (ctrl+shift+s, cmd+shift+s) Export to Binary File...`
`save (ctrl+s, cmd+s) Save file`

Those commands should also be available via the right-click menu.
