### ISSUE TITLE
Feature Request: Edit Mode

### ISSUE THREAD

**Issue by 1217950746** [stef-levesque/vscode-hexdump#56]

**Comment by stef-levesque** [comment]
I feel a complete edit mode is beyond the scope of this extension.
I feel that VSCode lack the flexibility to have such a complex UI.

But I'm open to ideas.

**Comment by irvnriir** [comment]
if you can render the current view, then it would be strange if you would be unable to make it Read And Write . the only thing really needed is event handler/-s in the byte and ASCII areas, that would give location of the changed text and the new text, all the rest is or done or just a calculations .

i didn't look in the VSC extensions dev-ing, and do not know what it has, but it too much looks accomplish-able .

**Comment by stef-levesque** [comment]
Microsoft is making it's own extension for [HexEditor](https://marketplace.visualstudio.com/items?itemName=ms-vscode.hexeditor)

I won't try to compete with them :)
