### ISSUE TITLE
Need to increase the max file size supported 

### ISSUE THREAD

**Issue by ktleach** [stef-levesque/vscode-hexdump#58]
How can I increase the max file size allowed?
It crashed (or times out) when you load a larger txt file.

**Comment by stef-levesque** [comment]
You can tweak the following values

`hexdump.sizeWarning` Display a warning if file is larger than this
`hexdump.sizeDisplay` Maximum size of the buffer to display

If the editor crash, or the buffer refuse to display, you likely hit the limit of VSCode.
