### ISSUE TITLE
Loss data on update

### ISSUE THREAD

**Issue by lexfrei** [stef-levesque/vscode-hexdump#63]
I'm writing to file and it looks like hexdump is not full. Random length on each run.
Full file each run in HxD.

Probably related to #2 or #39.

WIn10
VSCode 1.35.0
plugin 1.7.0

![image](https://user-images.githubusercontent.com/1366514/59391959-a11def00-8d7e-11e9-9e68-670eb80ce15b.png)

**Comment by stef-levesque** [comment]
Should be fixed in version 1.8.0
