### ISSUE TITLE
Encoding used in ASCII section

### ISSUE THREAD

**Issue by osharaki** [stef-levesque/vscode-hexdump#65]
I'm wondering why the following is being shown in the ASCII section instead of just ... (as other hex editors display) since these hex values have no mappings in ASCII.
![image](https://user-images.githubusercontent.com/38385026/63000763-3f5b2d80-be72-11e9-87ab-302c3c0e200f.png)

**Comment by stef-levesque** [comment]
From my understanding, hexy (the npm package used by this extension) will display Extended ASCII characters.
https://www.webopedia.com/TERM/E/extended_ASCII.html
