### ISSUE TITLE
Keyboard shortcut for hexdump.editvalue conflicts with built-in one

### ISSUE THREAD

**Issue by PaperCube** [stef-levesque/vscode-hexdump#69]
Key combination `Shift + Enter` was originally the same effect as `Enter`, but after installing hexdump this combination is bound to `hexdump.editvalue` globally, therefore in a normal text file this combination simply does nothing.

Currently I'm working around by changing the when expression to `editorTextFocus && editorLangId == 'hexdump'`. **I hope it can be made default** as it's essential for those who can't release their left shift in time when typing fast.

**Comment by iliazeus** [comment]
@PaperCube, I've resolved this issue in my fork: https://github.com/iliazeus/vscode-hexdump

I've changed the `when` expression to be `editorTextFocus && editorLangId == hexdump`, as per your suggestion.

[Marketplace link](https://marketplace.visualstudio.com/items?itemName=iliazeus.vscode-hexdump)

**Comment by stef-levesque** [comment]
Fixed in version 1.8.1
