### ISSUE TITLE
Are there defferences with vscode-hexdump by Ilia Pozdnyakov (Iliazeus)?

### ISSUE THREAD

**Issue by zarhani** [stef-levesque/vscode-hexdump#72]
There are two hexdumps in the vscode extensions store, but they are uploaded by different authors, and also the version number are different. Which should I install?

**Comment by yichengsu** [comment]
I recommend installing [Hex Editor](https://marketplace.visualstudio.com/items?itemName=ms-vscode.hexeditor), which is provided by Microsoft.

**Comment by stef-levesque** [comment]
Microsoft is making it's own Hex editor, so I won't try to compete with them :)
