### ISSUE TITLE
[bug] Show Hexdump button does nothing anymore

### ISSUE THREAD

**Issue by worstpractice** [stef-levesque/vscode-hexdump#75]
From VSCode's "about" panel:
- Version: 1.53.2 (user setup)
- Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
- Date: 2021-02-11T11:48:04.245Z
- Electron: 11.2.1
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Windows_NT x64 10.0.19042

I'm running vscode-hexdump 1.8.1.

Currently for me, right-clicking any file as usual and selecting "Show Hexdump" simply results in nothing happening.

No error message, but also no hexdump.

I tried watching for an error under the Output tab, but I couldn't find anything specifically related to vscode-hexdump in there.

Worth noting is that the "Show Hexdump" button always worked like a charm in the past. Been a month or two atleast since I last clicked it, but still.

Bugs happen. Thanks for a great extension anyhow.

**Comment by stef-levesque** [comment]
The extension works fine for me, both on macOS and Win10.
I can't tell what might goes wrong in your case. Maybe try to uninstall and reinstall the extension.
You might also want to try the Microsoft HexEditor extension.

Please reopen this issue if you have more info.
