### ISSUE TITLE
Un-deprecate extension in VSCode marketplace

### ISSUE THREAD

**Issue by davidva-ecco** [stef-levesque/vscode-hexdump#86]
This extension has been deprecated in the VSCode marketplace in favor of Hex Editor.  However, Hex Editor (as far as I can tell) does not have a true "hex dump" function that dumps the decoded hex data as ASCII text that can be edited/copy-pasted to another editor/reformatted.  I was using vscode-hexdump for this purpose but I am unable to install it now, due to it being deprecated:

![image](https://user-images.githubusercontent.com/26126030/179028738-72cbce73-b46a-4709-8733-faf2d06965df.png)

Can this extension be un-deprecated, or can someone recommend another way (in VSCode) to get an editable ASCII hex dump of a binary file?

**Comment by lramos15** [comment]
👋 , I'm the maintainer of the Hex Editor extension. I would be more than happy to take a PR to bring this as a command to the Hex Editor. If you don't have time for a PR feel free to submit a feature request and I or a community member may try to implement it.

In the meantime if the deprecation is causing you issues feel free to install it via the code cli `code --install-extension slevesque.vscode-hexdump` should do it 👍

**Comment by Tnze** [comment]
And HexEditor doesn't support export the binary file as C source code.

**Comment by etiennemlb** [comment]
And HexEditor suffer from feature creep which is not a problem as long as it is not laggy (which it is).
And HexEditor either does not does not seem to retain what work it has done and need to recompute lot of thing after a tab switch or there is a rendering issue. This makes it impossible to do a trivial visual tab comparison via fast tab switching (plain old Hyrum's law).
![hexeditor](https://user-images.githubusercontent.com/72296335/210538777-7e316487-0012-4089-ba52-3aa1a2973212.gif)
![hexdump](https://user-images.githubusercontent.com/72296335/210538780-ffe8b71f-4f9c-4fb9-9f74-12eaa203750a.gif)

**Comment by davidva-ecco** [comment]
Thanks everyone for your input, I have opened a feature request for this functionality in Hex Editor: https://github.com/microsoft/vscode-hexeditor/issues/411 so I am closing this issue.
