### ISSUE TITLE
Extension host terminated

### ISSUE THREAD

**Issue by Hackman1993** [stef-levesque/vscode-hexdump#9]
Maybe network problem,but always pop an Error:Extension host terminated unexpectedly,and the file will not open,does it really need to connect to a server?

**Comment by stef-levesque** [comment]
This seems more like a https://github.com/Microsoft/vscode issue.

Nonetheless, can you update the extension, and confirm if this happen to every files ? (small and large)

**Comment by Hackman1993** [comment]
It's the newest VSCode and the newest extension,and not every file happens,sometimes 1-3Mb happened,but sometimes ok

**Comment by Hackman1993** [comment]
thanks for the reply,by the way

**Comment by stef-levesque** [comment]
I added better support for large files, but it might still require some tweaking.

Can you tell me on what OS you are running? And could you provide a file causing the problem?

**Comment by Hackman1993** [comment]
Thank you very much,I updated the ext,and something still goes wrong,I'll provide the file I'm opening below,I change the ext name to zip for upload

[something_wrong_file.zip](https://github.com/stef-levesque/vscode-hexdump/files/555128/something_wrong_file.zip)

**Comment by stef-levesque** [comment]
Please update to version 1.1.2 and tell me if it solve the problem.

**Comment by Hackman1993** [comment]
sorry for reply you so slow,I just tried and the problem is gone,thanks a lot,I love it
